global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task-tracker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']  # или ваш локальный хост/порт
